# Generated by Django 4.2.30 on 2026-05-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("transactions", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="currency",
            field=models.CharField(
                choices=[
                    ("ARS", "Peso Argentino"),
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("CUSTOM", "Crear Nueva Moneda"),
                ],
                default="ARS",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="custom_currency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
